local_backend: true
backend:
  name: github
  repo: rabharta/rabharta.github.io
  branch: main
  use_graphql: true
  site_domain: rabhartagithubio.netlify.app
media_folder: /static/uploads/
public_folder: /uploads/
logo_url: /theme/images/an-rabharta-glas-logo.svg
publish_mode: editorial_workflow

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Homepage'
        name: 'homepage'
        file: 'content/_index.md'
        fields:
          - {label: 'Browser tab title', name: 'meta_title', required: false}
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Banner Heading', name: 'bannerheading', widget: 'text'}
          - {label: 'Banner Subheading', name: 'bannersubheading', widget: 'string'}
          - label: 'Banner Actions'
            name: 'banneractions'
            widget: 'list'
            fields:
              - {label: 'Label', name: 'action', widget: 'string'}
              # TODO: Make a custom relation widget to choose from all content
              - {label: 'Link', name: 'link', widget: 'string'}
          - {label: 'Content Heading', name: 'heading', widget: 'string'}
          - {label: 'Content Image', name: 'image', widget: 'image', choose_url: false}
          - {label: 'Content', name: 'body', widget: 'markdown'}
          - label: 'Content Actions'
            name: 'actions'
            widget: 'list'
            fields:
              - {label: 'Label', name: 'action', widget: 'string'}
              # TODO: Make a custom relation widget to choose from all content
              - {label: 'Link', name: 'link', widget: 'string'}
      - label: 'About page'
        name: 'about'
        file: 'content/about.md'
        fields:
          - {label: 'Browser tab title', name: 'meta_title', required: false}
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Subtitle', name: 'subtitle', widget: 'string'}
          - {label: 'Content', name: 'body', widget: 'markdown'}
      - label: 'People page'
        name: 'people'
        file: 'content/people/_index.md'
        fields:
          - {label: 'Browser tab title', name: 'meta_title', required: false}
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Content', name: 'body', widget: 'markdown'}
      - label: 'Values page'
        name: 'values'
        file: 'content/values.md'
        fields:
          - {label: 'Browser tab title', name: 'meta_title', required: false}
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Subtitle', name: 'subtitle', widget: 'string'}
          - {label: 'Banner Image', name: 'banner', widget: 'image', choose_url: false}
          - {label: 'Content', name: 'body', widget: 'markdown'}
          - label: 'Actions'
            name: 'actions'
            widget: 'list'
            fields:
              - {label: 'Label', name: 'action', widget: 'string'}
              # TODO: Make a custom relation widget to choose from all content
              - {label: 'Link', name: 'link', widget: 'string'}
      - label: 'Vision page'
        name: 'vision'
        file: 'content/vision/index.md'
        fields:
          - {label: 'Browser tab title', name: 'meta_title', required: false}
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Subtitle', name: 'subtitle', widget: 'string'}
          - {label: 'Banner Image', name: 'banner', widget: 'image', choose_url: false}
          - {label: 'Content', name: 'body', widget: 'markdown'}
          - label: 'Actions'
            name: 'actions'
            widget: 'list'
            fields:
              - {label: 'Label', name: 'action', widget: 'string'}
              # TODO: Make a custom relation widget to choose from all content
              - {label: 'Link', name: 'link', widget: 'string'}
  - name: 'programme'
    label: 'Programme pages'
    folder: 'content/policy/'
    create: true
    path: '{{title}}'
    # Note: Decap bug/peculiarity: need to specify media_folder & public_folder for each "folder" type collection (not required for "file" collections)
    media_folder: '{{media_folder}}'
    public_folder: '{{public_folder}}'
    fields:
      - {label: 'Browser tab title', name: 'meta_title', required: false}
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Banner Image', name: 'banner', widget: 'image', choose_url: false}
      - {label: 'Content', name: 'body', widget: 'markdown'}
      - label: 'Actions'
        name: 'actions'
        widget: 'list'
        fields:
          - {label: 'Label', name: 'action', widget: 'string'}
          # TODO: Make a custom relation widget to choose from all content
          - {label: 'Link', name: 'link', widget: 'string'}
  - name: 'people'
    label: 'Candidate profiles'
    folder: 'content/people/'
    path: '{{name}}'
    # Note: Decap bug/peculiarity: need to specify media_folder & public_folder for each "folder" type collection (not required for "file" collections)
    media_folder: '{{media_folder}}'
    public_folder: '{{public_folder}}'
    identifier_field: name
    # Note: hack to make "/people/" index page editable in CMS (instead of being a purely dynamic list page)
    filter: {field: list_page, value: false}
    create: true
    fields:
      # Part of above list_page hack
      - {label: 'List page hack', name: 'list_page', widget: 'hidden', default: false}
      - {label: 'Browser tab title', name: 'meta_title', required: false}
      - {label: 'Candidate name', name: 'title', widget: 'string'}
      - label: 'Constituency'
        name: 'constituency'
        widget: 'string'
      - {label: 'Candidate Photo', name: 'photo', widget: 'image', choose_url: false}
      - {label: 'Content', name: 'body', widget: 'markdown'}
      - label: 'Actions'
        name: 'actions'
        widget: 'list'
        fields:
          - {label: 'Label', name: 'action', widget: 'string'}
          # TODO: Make a custom relation widget to choose from all content
          - {label: 'Link', name: 'link', widget: 'string'}
  - name: 'blog'
    label: 'Blog Post'
    folder: 'content/posts/'
    # Note: Decap bug/peculiarity: need to specify media_folder & public_folder for each "folder" type collection (not required for "file" collections)
    media_folder: '{{media_folder}}'
    public_folder: '{{public_folder}}'
    create: true
    fields:
      - {label: 'Browser tab title', name: 'meta_title', required: false}
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Publish Date', name: 'date', widget: 'datetime'}
      - {label: 'Featured Image', name: 'thumbnail', widget: 'image', choose_url: false}
      - {label: 'Body', name: 'body', widget: 'markdown'}
  - name: 'contact-pages'
    label: 'Contact Pages'
    files:
      - label: 'Contact Page'
        name: 'contact-us'
        file: 'content/contact-us/_index.md'
        fields:
          - {label: 'Browser tab title', name: 'meta_title', required: false}
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Content', name: 'body', widget: 'markdown'}
      - label: 'Child Protection Officer'
        name: 'child-protection-officer'
        file: 'content/contact-us/child-protection-officer.md'
        fields:
          - {label: 'Browser tab title', name: 'meta_title', required: false}
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Content', name: 'body', widget: 'markdown'}
      - label: 'Contact Form Success Page'
        name: 'contact-us-sent'
        file: 'content/contact-us/sent.md'
        fields:
          - {label: 'Browser tab title', name: 'meta_title', required: false}
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Content', name: 'body', widget: 'markdown'}
      - label: 'Contact Form Error Page'
        name: 'contact-us-failure'
        file: 'content/contact-us/failure.md'
        fields:
          - {label: 'Browser tab title', name: 'meta_title', required: false}
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Content', name: 'body', widget: 'markdown'}
