local_backend: true
backend:
  name: github
  repo: rabharta/rabharta.github.io
  branch: main
  use_graphql: true
  # site_domain: rabhartagithubio.netlify.app
media_folder: static/uploads
public_folder: /uploads
logo_url: /theme/images/an-rabharta-glas-logo.svg

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Homepage'
        name: 'homepage'
        file: 'content/_index.md'
        fields:
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Banner Heading', name: 'bannerheading', widget: 'text'}
          - {label: 'Banner Subheading', name: 'bannersubheading', widget: 'string'}
          - label: 'Banner Actions'
            name: 'banneractions'
            widget: 'list'
            fields:
              - {label: 'Label', name: 'action', widget: 'string'}
              # TODO: Make a custom relation widget to choose from all content
              - {label: 'Link', name: 'link', widget: 'string'}
          - {label: 'Content Heading', name: 'heading', widget: 'string'}
          - {label: 'Content Image', name: 'image', widget: 'image'}
          - {label: 'Content', name: 'body', widget: 'markdown'}
          - label: 'Content Actions'
            name: 'actions'
            widget: 'list'
            fields:
              - {label: 'Label', name: 'action', widget: 'string'}
              # TODO: Make a custom relation widget to choose from all content
              - {label: 'Link', name: 'link', widget: 'string'}
      - label: 'About page'
        name: 'about'
        file: 'content/about.md'
        fields:
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Subtitle', name: 'subtitle', widget: 'string'}
          - {label: 'Content', name: 'body', widget: 'markdown'}
      - label: 'People page'
        name: 'people'
        file: 'content/people/_index.md'
        fields:
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Content', name: 'body', widget: 'markdown'}
      - label: 'Values page'
        name: 'values'
        file: 'content/values.md'
        fields:
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Subtitle', name: 'subtitle', widget: 'string'}
          - {label: 'Banner Image', name: 'banner', widget: 'image', choose_url: false}
          - {label: 'Content', name: 'body', widget: 'markdown'}
          - label: 'Actions'
            name: 'actions'
            widget: 'list'
            fields:
              - {label: 'Label', name: 'action', widget: 'string'}
              # TODO: Make a custom relation widget to choose from all content
              - {label: 'Link', name: 'link', widget: 'string'}
      - label: 'Vision page'
        name: 'vision'
        file: 'content/vision/index.md'
        fields:
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Subtitle', name: 'subtitle', widget: 'string'}
          - {label: 'Banner Image', name: 'banner', widget: 'image', choose_url: false}
          - {label: 'Content', name: 'body', widget: 'markdown'}
          - label: 'Actions'
            name: 'actions'
            widget: 'list'
            fields:
              - {label: 'Label', name: 'action', widget: 'string'}
              # TODO: Make a custom relation widget to choose from all content
              - {label: 'Link', name: 'link', widget: 'string'}
  - name: 'programme'
    label: 'Programme pages'
    folder: 'content/policy/'
    create: true
    path: '{{title}}'
    fields:
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Banner Image', name: 'banner', widget: 'image', choose_url: false}
      - {label: 'Content', name: 'body', widget: 'markdown'}
      - label: 'Actions'
        name: 'actions'
        widget: 'list'
        fields:
          - {label: 'Label', name: 'action', widget: 'string'}
          # TODO: Make a custom relation widget to choose from all content
          - {label: 'Link', name: 'link', widget: 'string'}
  - name: 'people'
    label: 'Candidate profiles'
    folder: 'content/people/'
    path: '{{name}}'
    identifier_field: name
    filter: {field: list_page, value: false}
    create: true
    fields:
      - {label: 'Name', name: 'name', widget: 'string'}
      - label: 'Constituency'
        name: 'constituency'
        widget: 'string'
        # widget: 'select'
        # options: ['Belfast East BC', 'Belfast North BC', 'Belfast South BC', 'Belfast West BC', 'Carlow-Kilkenny', 'Cavan-Monaghan', 'Clare', 'Cork East', 'Cork North-Central', 'Cork North-West', 'Cork South-Central', 'Cork South-West', 'Donegal', 'Dublin Bay North', 'Dublin Bay South', 'Dublin Central', 'Dublin Fingal', 'Dublin Mid-West', 'Dublin North-West', 'Dublin Rathdown', 'Dublin South-Central', 'Dublin South-West', 'Dublin West', 'Dún Laoghaire', 'East Antrim CC', 'East Londonderry CC', 'Fermanagh & South Tyrone CC', 'Foyle CC', 'Galway East', 'Galway West', 'Kerry', 'Kildare North', 'Kildare South', 'Lagan Valley CC', 'Laois-Offaly', 'Limerick City', 'Limerick County', 'Longford-Westmeath', 'Louth', 'Mayo', 'Meath East', 'Meath West', 'Mid Ulster CC', 'Newry & Armagh CC', 'North Antrim CC', 'North Down CC', 'Roscommon-Galway', 'Sligo-Leitrim', 'South Antrim CC', 'South Down CC', 'Strangford CC', 'Tipperary', 'Upper Bann CC', 'Waterford', 'West Tyrone CC', 'Wexford', 'Wicklow']
      - {label: 'Candidate Photo', name: 'photo', widget: 'image', choose_url: false}
      - {label: 'Content', name: 'body', widget: 'markdown'}
      - label: 'Actions'
        name: 'actions'
        widget: 'list'
        fields:
          - {label: 'Label', name: 'action', widget: 'string'}
          # TODO: Make a custom relation widget to choose from all content
          - {label: 'Link', name: 'link', widget: 'string'}
  - name: 'contact-pages'
    label: 'Contact Pages'
    files:
      - label: 'Contact Page'
        name: 'contact-us'
        file: 'content/contact-us.md'
        fields:
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Content', name: 'body', widget: 'markdown'}
      - label: 'Child Protection Officer'
        name: 'child-protection-officer'
        file: 'content/contact-us/child-protection-officer.md'
        fields:
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Content', name: 'body', widget: 'markdown'}
      - label: 'Contact Form Success Page'
        name: 'contact-us-sent'
        file: 'content/contact-us/sent.md'
        fields:
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Content', name: 'body', widget: 'markdown'}
      - label: 'Contact Form Error Page'
        name: 'contact-us-failure'
        file: 'content/contact-us/failure.md'
        fields:
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Content', name: 'body', widget: 'markdown'}
